### ISSUE TITLE
More meta-programming for documentation and testing

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#771]
Currently the metrics repositories images are generated and hosted on my personal repository [lowlighter/lowlighter](https://github.com/lowlighter/lowlighter) but I'd like to move them here instead.

This is also the occasion for a refactoring of documentation, examples and testing.
The aim is to combine them all: examples will be used for both illustrative purposes and as test cases, and will also be reused in documentation. 

Additionally, options will be directly visible from plugin documentation (rather than reading the `metadata.yml`) and will also contain whether the option is new (i.e. a beta feature).

- [x] Create an orphan branch [`examples`](https://github.com/lowlighter/metrics/tree/examples)
  - [x] Auto-generate production workflow from `examples.yml`
  - [x] Auto-generate tests workflows from `examples.yml`
  - [x] Remove `tests.yml`
- [x] Migrate workflows steps from [lowlighter/lowlighter](https://github.com/lowlighter/lowlighter) to [lowlighter/metrics](https://github.com/lowlighter/metrics)
  - [x] Plugins
  - [x] Templates
  - [x] Other 
- [x] Auto-generate workflows examples 
  - [x] In plugins documentation
  - [x] In templates documentation
- [x] Auto-generate options and typing
  - [x] In plugins documentation
  - [x] In templates documentation
- [x] Test whole ci to ensure it's not broken
